# Site
repository: xdjia/xdjia.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Xiaodong Jia
title: Ph.D. Candidate
email: xxj34@psu.edu
website: https://xdjia.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: xdjia
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: xdjia
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello and welcome to my personal page! My name is Xiaodong Jia, and I am currently a dedicated Ph.D. candidate in the Computer Science and Engineering (CSE) department at the Pennsylvania State University.

  Throughout my academic journey, I have developed a strong passion for several key areas within the field of computer science. My main research interests encompass formal verification, parsing, grammar inference, and machine learning. As an avid researcher, I strive to contribute to the ongoing advancements in these fields by exploring innovative solutions and pushing the boundaries of our current knowledge.

  I am most skilled in: <mark>Python</mark>, <mark>PyTorch</mark>, <mark>Coq</mark>, <mark>OCaml</mark>, and <mark>Haskell</mark>.

content:
  - title: Research Interest
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Formal verification.
      - Parsing.
      - Grammar inference.
      - Machine learning.
  - title: Publications 
    layout: text
    content: | # this will include new lines to allow paragraphs
      [1]. Xiaodong Jia, Ashish Kumar, and Gang Tan. 2023. A Derivative-Based Parser Generator for Visibly Pushdown Grammars. ACM Trans. Program. Lang. Syst. (TOPLAS) Just Accepted (April 2023). https://doi.org/10.1145/3591472 [PDF](https://dl.acm.org/doi/pdf/10.1145/3591472)

      [2]. Xiaodong Jia, Ashish Kumar, and Gang Tan. 2021. A derivative-based parser generator for visibly Pushdown grammars. Proc. ACM Program. Lang. 5, OOPSLA, Article 151 (October 2021), 24 pages. https://doi.org/10.1145/3485528 [PDF](https://dl.acm.org/doi/pdf/10.1145/3485528)

      [3]. He, J., Jia, X., Xu, J. et al. Make ℓ1 regularization effective in training sparse CNN. Comput Optim Appl 77, 163–182 (2020). https://doi.org/10.1007/s10589-020-00202-1 [PDF](https://arxiv.org/pdf/1807.04222.pdf)
  
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
